---
sidebar: sidebar
permalink: upgrade-arl-auto-in-chassis/decide-to-use-the-aggregate-relocation-guide.html
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability
summary: "Decide whether to use the ARL procedure that upgrades controller models in the same chassis."
---
= Decide whether to use this aggregate relocation procedure
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
There are several aggregate relocation (ARL) methods for upgrading controller hardware. This content describes how to upgrade storage controllers in an HA pair by converting the existing system to the replacement system, keeping the existing system chassis and disks. You should only use this complex procedure if you're an experienced ONTAP administrator.

To help you decide if this ARL procedure is suitable for your controller hardware upgrade, you should review all of the following circumstances for supported and unsupported upgrades.

== Supported for this ARL upgrade
You can use this ARL procedure under the following circumstances:

* Your controller upgrade is listed in the <<supported-systems,supported systems matrix>>.
* You have verified with your NetApp sales representative that you have received the hardware that you need for the controller upgrade:
** Two AFF A90, AFF A70, or AFF C80 controllers and all I/O modules. The required lengths of 100GbE cables.
** Two AFF A50, AFF A30, AFF C30, or AFF C60 controllers and I/O modules and the required cables
** ASA A150, AFF A150, or FAS2820 controller
** ASA A900, AFF A900, or FAS9500 controller and NVRAM modules and parts

* You're running the minimum ONTAP version for your upgrade. For more information, refer to the <<supported-systems,supported system upgrade combinations>>.
* You're experienced in administering ONTAP and are comfortable with the risks of working in diagnostic privilege mode.
* Your systems are running ONTAP 9.15.1 or later, and they are using Ethernet switches to connect to Ethernet-attached storage.

NOTE: You can use NetApp Storage Encryption (NSE), NetApp Volume Encryption (NVE), and NetApp Aggregate Encryption (NAE) with this procedure.

== Not supported for this ARL upgrade
You cannot use this ARL procedure under the following circumstances:

* You want to add the new controllers as a new HA pair to the cluster and migrate the data by using volume moves.
* You're upgrading a MetroCluster IP configuration. 
+
To upgrade a MetroCluster IP configuration, see link:other_references.html[References] to link to the _MetroCluster Upgrade and Expansion_ content.

[[supported-systems]]
== Supported system upgrade combinations

The following table shows the supported systems matrix for performing a controller upgrade by converting the existing system to the replacement system, keeping the existing system chassis and disks.

CAUTION: This procedure strictly applies to the following upgrade configurations. Don't use this procedure to perform an upgrade between any other system combinations. For all other controller models, refer to link:other_references.html[References] to link to _Use "system controller replace" commands to upgrade controller hardware running ONTAP 9.8 or later_ and _Using aggregate relocation to manually upgrade controller hardware running ONTAP 9.8 or later_.

[[supported-systems-in-chassis]]
[cols=3*,options="header",cols="20,20,40"]
|===
|Existing system |Replacement system |Supported ONTAP versions
|AFF C250 ^1^
|AFF C30, AFF C60
|9.16.1
|AFF A250 ^1^
|AFF A30, AFF A50
|9.16.1 
|AFF C800 ^1^
|AFF C80
|9.16.1 
|AFF A800 ^1^
|AFF A90 or AFF A70
|9.15.1 and later
|AFF A220 configured as an All SAN Array (ASA) 
|ASA A150
|9.13.1P1 and later
|AFF A220
|AFF A150
|9.10.1P15, 9.11.1P11, 9.12.1P5 and later
|AFF A200 
|AFF A150
a|9.10.1P15, 9.11.1P11 and later ^2^

|AFF C190
|AFF A150
|9.10.1P15, 9.11.1P11, 9.12.1P5 and later 

|FAS2620 
|FAS2820
a|9.11.1P7 or later patch releases (FAS2620) ^2^

9.13.1 and later (FAS2820)
|FAS2720 |FAS2820	
|9.13.1 and later
|AFF A700 configured as an ASA 
|ASA A900
|9.13.1P1 and later
|AFF A700 
|AFF A900
|9.10.1P10, 9.11.1P6 and later
|FAS9000 |FAS9500
|9.10.1P10, 9.11.1P6 and later
|===

^1^ When you upgrade to a system introduced in ONTAP 9.15.1 or later, ONTAP converts the storage efficiency of all existing thin-provisioned volumes, including those not using storage efficiency, and applies the new storage efficiency features that make use of the hardware offload functionality. This is an automatic background process, with no visible performance impact to the system. https://docs.netapp.com/us-en/ontap/concepts/builtin-storage-efficiency-concept.html[Learn more^].

^2^ The AFF A200 and FAS2620 systems don't support ONTAP versions later than 9.11.1.

[NOTE]
====
NetApp strongly recommends, when possible, that you have the same ONTAP version on the old and replacement systems.

The minimum ONTAP versions in the preceding table are mandatory. These ONTAP versions have the Service Processor or baseboard management controller (BMC) firmware version that is required to support mixing controller types within a chassis during an upgrade. 
====

include::../_include/ru_all_decide_use_arl_guide_end.adoc[]

// 2025 FEB 25, AFFFASDOC-284
// 2024 DEC 9, AFFFASDOC-33
// 2024 DEC 5, AFFFASDOC-273
// 2024 APR 16, AFFFASDOC-32
// 2023 AUG 29, AFFFASDOC-78
// 2023 MAY 29, AFFFASDOC-39
// 2022 Jan 30, BURT 1523106
// 2022 APR 26, BURT 1452254 
