---
sidebar: sidebar
permalink: upgrade-arl-auto-in-chassis/install-asa150-affa150-fas2820-on-node2.html
keywords: aff, fas, asa, install, NVRAM, node2, controller, module, modules, replacement
summary: "Install the replacement system modules on node2 during an ARL upgrade of controller models in the same chassis."
---
= Install the ASA A150, AFF A150, or FAS2820 controller module on node2
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Install the ASA A150, AFF A150 or FAS2820 controller module that you received for the upgrade on node2. Node2 is controller B located on the right side of the chassis when looking at the controllers from the rear of the system.

.Before you begin

* If you are not already grounded, correctly ground yourself.
* Disconnect all the cables, including console, management, SAS storage, and data network cables, from the controller being removed.

.Steps

. Align the end of the controller module with bay B in the chassis, and then gently push the controller module halfway into the system.
+
TIP: Bay B is located on the right side of the chassis.
+
WARNING: Don't completely insert the controller module in the chassis until you are instructed to do so later in the procedure.

. Cable the management and console ports to the node2 controller module.
+
NOTE: Because the chassis is already powered ON, node2 starts booting as soon as it is fully seated.To prevent node2 from booting, connect the console and management cables before fully inserting the controller module.

. Firmly push the controller module into the chassis until it meets the midplane and is fully seated.
+
The locking latch rises when the controller module is fully seated.
+
NOTE: To avoid damaging the connectors, don't use excessive force when sliding the controller module into the chassis.

. Connect the serial console as soon as the module is seated and be ready to interrupt AUTOBOOT of node2.
. After you interrupt AUTOBOOT, node2 stops at the LOADER prompt. If you do not interrupt AUTOBOOT on time and node2 starts booting, wait for the prompt and press Ctrl-C to go into the boot menu. After the node stops at the boot menu, use option `8` to reboot the node and interrupt AUTOBOOT during reboot.


// 2025 JUN 19, AFFFASDOC-334
// 2025 Aug 09, AFFFASDOC-378
// 2023 AUG 29, AFFFASDOC-78
// 2023 MAY 29, AFFFASDOC-39
// 2023-MAR-3, ontap-systems-upgrade/issues/78
// 2022-OCT-24, BURT 1506458 
// 2022-APR-27, BURT 1452254
