---
sidebar: sidebar
permalink: upgrade-arl-auto-in-chassis/move-non-root-aggr-and-nas-data-lifs-back-to-node2.html
keywords: moving, non-root, aggregates, nas, lif, node1, node2
summary: "Verify that node2's NAS data LIFs on node1 are relocated from node1 to node2 when using ARL to upgrade controller models in the same chassis."
---
= Move non-root aggregates and NAS data LIFs back to node2
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
After verifying the network configuration on node2, you need to relocate the NAS data LIFs owned by node2 from node1 to node2 and confirm that the SAN LIFs exist on node2.

.About this task
Remote LIFs handle traffic to SAN LUNs during the upgrade procedure. Moving SAN LIFs is not necessary for cluster or service health during the upgrade. SAN LIFs are not moved unless they need to be mapped to new ports. 

You verify that the LIFs are healthy and located on the correct ports after you bring node2 online.

.Steps
. Resume the relocation operation:
+
[source,cli]
----
system controller replace resume
----
+
The system performs the following tasks:
+
--
* Cluster quorum check
* System ID check
* Image version check
* Target platform check
* Network reachability check
--
+
The system pauses the operation at this stage in the network reachability check

. Resume the relocation operation:
+
[source,cli]
----
system controller replace resume
----
+
The system performs the following checks:
+
--
* Cluster health check
* Cluster LIF status check
--
+
After performing these checks, the system relocates the non-root aggregates and NAS data LIFs back to node2, which is now running on the replacement controller.
+
The controller replacement operation pauses after the resource relocation is complete.

. Check the status of the aggregate relocation and NAS data LIF move operations:
+
[source,cli]
----
system controller replace show-details
----
+
If the controller replacement procedure is paused, check and correct the error, if any, and then issue `resume` to continue the operation.

. If necessary, restore and revert displaced LIFs or manually migrate and modify the node2 LIFs that failed to relocate automatically to node2.
+
[role="tabbed-block"]
====
.Restore and revert displaced LIFs
--
.. List any displaced LIFs:
+
[source,cli]
----
cluster controller-replacement network displaced-interface show
----

.. If any LIFs are displaced, restore the home node back to node2:
+
[source,cli]
----
cluster controller-replacement network displaced-interface restore-home-node -node <node2_nodename> -vserver <vserver name> -lif-name <lif_name>
----
--

.Manually migrate and modify LIFs
--
.. Migrate the LIFs that failed to relocate automatically to node2:
+
[source,cli]
----
network interface migrate -vserver <vserver name> -lif <lif_name> -destination-node <node2_nodename> -destination-port <port_on_node2>
----

.. Modify the home node and home port for the migrated LIFs:
+
[source,cli]
----
network interface modify -vserver <vserver_name> -lif <data_lif_name> -home-node <node2_nodename> -home-port <home_port>
----
--
====

. Resume the operation to prompt the system to perform the required post-checks:
+
[source,cli]
----
system controller replace resume
----
+
The system performs the following post-checks:

* Cluster quorum check
* Cluster health check
* Aggregates reconstruction check
* Aggregate status check
* Disk status check
* Cluster LIF status check
* Volume check

// 2025 SEP 19, AFFFASDOC-335