---
sidebar: sidebar
permalink: upgrade-arl-auto-in-chassis/prepare-nodes-for-upgrade.html
keywords: preparing, prepare, nodes, upgrade, stage 1, prechecks, old, system, chassis, disk, disks
summary: "Prepare the nodes and run a series of prechecks when using ARL to upgrade controller models in the same chassis."
---
= Prepare the nodes for upgrade
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
The controller replacement process begins with a series of prechecks. You also gather information about the original nodes for use later in the procedure and, if required, determine the type of self-encrypting drives that are in use.

== Step 1: Prepare the nodes

Start the controller replacement process and run prechecks. If required, determine the type of self-encrypting drives that are in use.

.Steps

. List the Service Processor (SP) or baseboard management controller (BMC) firmware version running on the old controller: 
+
[source,cli]
----
service-processor show
----
+
Verify that you have a supported SP or BMC firmware version:
+
[cols=3*,options="header",cols="30,35,35"]
|===
|Old controller
|SP or BMC
|Minimum firmware version

|AFF A800
|BMC
|10.9
|AFF A220
|BMC	
|11.9P1 
|AFF A200		
|SP
|5.11P1 
|AFF C190		
|BMC	
|11.9P1 
|FAS2620
|SP
|5.11P1
|FAS2720
|BMC
|11.9P1
|===

. Begin the controller replacement process by entering the following command in the advanced privilege mode of the ONTAP command line:
+
[source,cli]
----
set -privilege advanced
----
+
[source,cli]
----
system controller replace start -nodes <node_names>
----
+
You see output similar to the following example. The output displays the ONTAP version running on your cluster:
+
....
Warning:
1. Current ONTAP version is 9.15.1

2. Verify that NVMEM or NVRAM batteries of the new nodes are charged, and charge them if they are not. You need to physically check the new nodes to see if the NVMEM or NVRAM  batteries are charged. You can check the battery status either by connecting to a serial console or using SSH, logging into the Service Processor (SP) or Baseboard Management Controller (BMC) for your system, and use the system sensors to see if the battery has a sufficient charge.

Attention: Do not try to clear the NVRAM contents. If there is a need to clear the contents of NVRAM, contact NetApp technical support.

3. If a controller was previously part of a different cluster, run wipeconfig before using it as the replacement controller.

4. Note: This is not a MetroCluster configuration. Controller replacement supports only ARL based procedures.

Do you want to continue? {y|n}: y
....
+
. Select `y`. You see the following output:
+
....
Controller replacement operation: Prechecks in progress.
Controller replacement operation has been paused for user intervention.
....
+
During the prechecks phase, the system runs the following list of checks in the background.
+
[cols="35,65"]
|===
|Precheck |Description

|Cluster Health Check
|Checks all the nodes in the cluster to confirm that they are healthy.
|Aggregate Relocation Status Check
|Checks whether an aggregate relocation is already in progress.
If another aggregate relocation is in progress, the check fails.
|Model Name Check
|Checks whether the controller models are supported for this procedure.
If the models are not supported, the task fails.
|Cluster Quorum Check
|Checks that the nodes being replaced are in quorum. If the nodes are not in quorum, the task fails.
|Image Version Check
|Checks that the nodes being replaced run the same version of ONTAP.
If the ONTAP image versions are different, the task fails.
The new nodes must have the same version of ONTAP 9.x installed on them that is installed on the original nodes. If the new nodes have a different version of ONTAP installed, you need to netboot the new controllers after you install them. For instructions on how to upgrade ONTAP, refer to link:other-references.html[References] to link to _Upgrade ONTAP_.
|HA Status Check
|Checks if both the nodes being replaced are in a high availability (HA) pair configuration.
If storage failover is not enabled for the controllers, the task fails.
|Aggregate Status Check
|If the nodes being replaced own aggregates for which they are not the home owner, the task fails.
The nodes should not own any non-local aggregates.
|Disk Status Check
|If any nodes being replaced have missing or failed disks, the task fails.
If any disks are missing, refer to link:other-references.html[References] to link to _Disk and aggregate management with the CLI_,  _Logical storage management with the CLI_, and _HA pair management_ to configure storage for the HA pair.
|Data LIF Status Check
|Checks if any of the nodes being replaced have non-local data LIFs.
The nodes should not contain any data LIFs for which they are not the home owner. If one of the nodes contains non-local data LIFs, the task fails.
|Cluster LIF Status
|Checks whether the cluster LIFs are up for both nodes. If the cluster LIFs are down, the task fails.
|ASUP Status Check
|If AutoSupport notifications are not configured, the task fails.
You must enable AutoSupport before beginning the controller replacement procedure.
|CPU Utilization Check
|Checks if the CPU utilization is more than 50% for any of the nodes being replaced.
If the CPU usage is more than 50% for a considerable period of time, the task fails.
|Aggregate Reconstruction Check
|Checks if reconstruction is occurring on any data aggregates.
If aggregate reconstruction is in progress, the task fails.
|Node Affinity Job Check
|Checks if any node affinity jobs are running.
If node affinity jobs are running, the check fails.
|===

.	After the controller replacement operation is started and the prechecks are completed, the operation pauses, enabling you to collect output information that you might need later in the controller upgrade process.

. Run the below set of commands as directed by the controller replacement procedure on the system console.
+
Run the commands from the serial port connected to each node, run and save the output of the commands individually:
+
[source,cli]
----
vserver services name-service dns show
----
+
[source,cli]
----
network interface show -curr-node <local> -role cluster,intercluster,node-mgmt,cluster-mgmt,data
----
+
[source,cli]
----
network port show -node <local> -type physical
----
+
[source,cli]
----
service-processor show -node <local> -instance
----
+
[source,cli]
----
network fcp adapter show -node <local>
----
+
[source,cli]
----
network port ifgrp show -node <local>
----
+
[source,cli]
----
system node show -instance -node <local>
----
+
[source,cli]
----
run -node <local> sysconfig
----
+
[source,cli]
----
run -node local sysconfig -ac
----
+
[source,cli]
----
run -node local aggr status -r
----
+
[source,cli]
----
vol show -fields type
----
+
[source,cli]
----
run local aggr options <data_aggregate_name>
----
+
[source,cli]
----
vol show -fields type , space-guarantee
----
+
[source,cli]
----
storage aggregate show -node <local>
----
+
[source,cli]
----
volume show -node <local>
----
+
[source,cli]
----
storage array config show -switch <switch_name>
----
+
[source,cli]
----
system license show -owner <local>
----
+
[source,cli]
----
storage encryption disk show
----
+
[source,cli]
----
security key-manager onboard show-backup
----
+
[source,cli]
----
security key-manager external show
----
+
[source,cli]
----
security key-manager external show-status
----
+
[source,cli]
----
network port reachability show -detail -node <local>
----
+
NOTE: If NetApp Volume Encryption (NVE) or NetApp Aggregate Encryption (NAE) using the Onboard Key Manager is in use, keep the key-manager passphrase ready to complete the key manager resync later in the procedure.

. If your system uses self-encrypting drives, see the Knowledge Base article https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified[How to tell if a drive is FIPS certified^] to determine the type of self-encrypting drives that are in use on the HA pair that you are upgrading. ONTAP software supports two types of self-encrypting drives:
+
--
* FIPS-certified NetApp Storage Encryption (NSE) SAS or NVMe drives
* Non-FIPS self-encrypting NVMe drives (SED)

[NOTE]
====
You cannot mix FIPS drives with other types of drives on the same node or HA pair.

You can mix SEDs with non-encrypting drives on the same node or HA pair.
====

https://docs.netapp.com/us-en/ontap/encryption-at-rest/support-storage-encryption-concept.html#supported-self-encrypting-drive-types[Learn more about supported self-encrypting drives^]. 
--

include::../_include/ru_auto_correct_aggregate_ownership.adoc[]

.What's next?
After preparing the nodes, link:complete-preparation-for-upgrade.html[complete the preparation for upgrade].

// 2023 MAY 29, AFFFASDOC-39
// 2023 APR 11, ontap-systems-upgrade-issues-64/BURT 1519747
// 2022 DEC 1, ontap-systems-upgrade-37
// 2022 MAY 16, BURT 1476251
