---
permalink: choose_controller_upgrade_procedure.html
sidebar: sidebar
keywords: 
summary: In general, how you upgrade the controller hardware depends on the platform models of the original nodes. You upgrade either by moving aggregates or volumes storage (nondisruptive procedures) or by moving storage (a disruptive procedure).
---
= Choose your controller hardware upgrade procedure
:icons: font
:imagesdir: ./media/

[.lead]
In general, how you upgrade the controller hardware depends on the platform models of the original nodes. You upgrade either by relocating aggregates or moving volumes (both nondisruptive procedures), or by moving the storage (a disruptive procedure). If you have different ONTAP versions running on the original and new nodes, you might need to perform a software upgrade before starting the hardware upgrade.

NOTE: ASA upgrades to an ASA r2 replacement system aren't supported. For information on migrating data from an ASA to ASA r2 system, see link:https://docs.netapp.com/us-en/asa-r2/install-setup/set-up-data-access.html[Enable data access from SAN hosts to your ASA r2 storage system^].


To select the appropriate upgrade procedure, review all the questions listed in the table below.

.Show example answers
[%collapsible]
====
This example shows the possible answers for a FAS9500 to FAS90 controller upgrade.

[cols=2*,options="header",cols="30,70"]
|===
| Question | Example answer

| Am I running a different software version on the original and new nodes?
| No. Both FAS9500 and FAS90 run ONTAP 9.15.1.

| Do I want to do a disruptive upgrade?
| No. I want to keep my production environment online during the upgrade.

| Do I want to do a non-disruptive upgrade?
| Yes. Based on whether my system is modular or integrated, I can upgrade by moving volumes or using aggregate relocation (ARL).

| Do I have a modular system?
| Yes. The FAS9500 is a modular system with external storage shelves. I can upgrade by using ARL.

| Do I have an integrated system and want to upgrade by moving volumes?
| No. The FAS9500 is a modular system, so this doesn't apply.

| Do I have an integrated system and want to upgrade by swapping the controller module only, keeping existing chassis and disks?
| No. The FAS9500 is a modular system, so this doesn't apply.

| Am I relocating an SVM?
| No. I'm upgrading the hardware while keeping the same SVMs.

| Am I upgrading a MetroCluster configuration?
| No. This is a standard HA pair cluster.

| Am I replacing an individual component?
| No. I'm upgrading the entire controller system.
|===

*Recommended upgrade path for this example:* link:upgrade-arl/index.html[Upgrade by using aggregate relocation] because the FAS9500 is a modular system and ARL provides a non-disruptive upgrade method.
====

[cols=2*,options="header",cols="30,70"]
|===
| Ask yourself…	| If your answer is yes, you can do this…
| Am I running a different software version on the original and new nodes?	

| Upgrade the ONTAP version on the original nodes to the maximum supported version.

The new nodes must support the ONTAP version running on the original nodes. If required, link:https://docs.netapp.com/us-en/ontap/upgrade/prepare.html[upgrade the ONTAP version^] on the original nodes to the maximum supported version. The version difference between the original and new nodes cannot be greater than four. For example, ONTAP 9.8 and 9.12.1 is supported; however, ONTAP 9.8 and 9.13.1 is not supported. link:https://docs.netapp.com/us-en/ontap/upgrade/concept_mixed_version_requirements.html[Learn more about mixed version ONTAP clusters^].

| Do I want to do a disruptive upgrade?	
| link:upgrade/upgrade-decide-to-use-this-guide.html[Upgrade by moving storage].

This requires a new system with its own storage and shelves to store the data from the original system. Conversion from a controller shelf is possible for certain upgrades.

| Do I want to do a non-disruptive upgrade?	

a| Upgrade by using one of the following methods:

* link:upgrade/upgrade-decide-to-use-this-guide.html[Move volumes]
+
This requires joining the new nodes, moving the volumes and LIFs to the new nodes, and unjoining the nodes you want to remove from the cluster. If you are upgrading a two-node switchless cluster, convert it to a switched attached cluster using a pair of cluster switches before adding new nodes.
* link:upgrade-arl/index.html[Use aggregate relocation]
+
ARL is a replacement procedure. You do not need to expand and shrink your cluster with the new nodes, which is beneficial for two-node switchless clusters. Moving data by relocating aggregates is faster than copying data across aggregates when moving volumes.

| Do I have a modular system?

*Note*: In a modular system, the controller does not have any internal disks and all storage is in externally attached shelves.

| link:upgrade-arl/index.html[Upgrade by using aggregate relocation].

| Do I have an integrated system and want to upgrade by moving volumes?	

*Note*: In an integrated system, the controller has internal disks and the storage is contained within the controller chassis and in externally attached shelves. External shelves are for storage expansion and might not be included in every system configuration.

a| . link:https://hwu.netapp.com/DetailViews/Home.aspx[Verify that your system is supported^].
. link:upgrade/upgrade-decide-to-use-this-guide.html[Upgrade by moving volumes].

| Do I have an integrated system and want to upgrade by swapping the controller module only, keeping existing chassis and disks?
| link:upgrade-arl-auto-affa900/index.html[Upgrade by using ARL, keeping the same chassis and disks].

| Am I relocating an SVM? 
| Refer to link:https://docs.netapp.com/us-en/ontap/svm-migrate/index.html#svm-migration-workflow[SVM data mobility overview^].

| Am I upgrading a MetroCluster configuration?
|Refer to link:https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html[Upgrade, refresh, or expand the MetroCluster configuration^].

| Am I replacing an individual component?
| Refer to the link:https://docs.netapp.com/us-en/ontap-systems/index.html[ONTAP Hardware Systems Documentation^] and locate the field-replaceable unit (FRU) flyer for that component.
|===

// 2025 OCT 17, AFFFASDOC-404
// 2023 NOV 16, BURT 1552664