---
settings:
  name: Upgrade controllers
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: ONTAP Hardware Upgrade Documentation
      url: /index.html
    - title: Choose your controller hardware upgrade procedure
      url: /choose_controller_upgrade_procedure.html
    - section: upgrade-arl
    - title: Upgrade controllers models in the same chassis
      entries:
      - section: upgrade-arl-auto-affa900
    - title: Use "system controller replace" commands
      entries:
      - section: upgrade-arl-auto-app
      - section: upgrade-arl-auto
    - title: Use manual commands
      entries:
      - section: upgrade-arl-manual-app
      - section: upgrade-arl-manual
    - section: upgrade
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: ONTAP hardware systems
  repo: ontap-systems-family