sidebar:
  entries:
    - title: AFF and FAS System Upgrade Documentation
      url: /index.html
    - section: upgrade
    - section: upgrade-arl-auto-app
    - section: upgrade-arl-manual-app
    - section: upgrade-arl-auto
    - section: upgrade-arl-manual

homepage:
  tiles:
    - title: Upgrade by moving storage or volumes (most systems)
      links:
        - title: Upgrade controller hardware
          url: /upgrade/index.html
    - title: Upgrade by moving aggregates on systems running ONTAP 9.8 and later
      links:
        - title: Use "system controller replace" commands (most systems)
          url: https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-app/
        - title: Use manual commands
          url: https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-manual-app/
    - title: Upgrade by moving aggregates on systems running ONTAP 9.7 and earlier
      links:
        - title: Use “system controller replace” commands
          url: https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto/
        - title: Use manual commands
          url: https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-manual/
    - title: Upgrade systems in a MetroCluster configuration
      links:
        - title: Select the upgrade procedure for your MetroCluster configuration
          url: https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html
