---
settings:
  name: Upgrade controllers
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: Choose your controller hardware upgrade procedure
      url: /choose_controller_upgrade_procedure.html
    - title: ONTAP Hardware Upgrade Documentation
      url: /index.html
    - title: Upgrade by using ARL
      entries:
      - section: upgrade-arl-auto-app-9151
      - section: upgrade-arl
      - section: upgrade-arl-auto-affa900
      - section: upgrade-arl-auto-app
      - section: upgrade-arl-auto
      - section: upgrade-arl-manual-app
      - section: upgrade-arl-manual
    - section: upgrade
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: ONTAP hardware systems
  repo: ontap-systems-family