---
settings:
  name: Upgrade controllers
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: AFF and FAS System Upgrade Documentation
      url: /index.html
    - title: Choose your controller hardware upgrade procedure
      url: /choose_controller_upgrade_procedure.html
    - section: upgrade-arl
    - section: upgrade
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: AFF and FAS Systems
  repo: ontap-systems-family