---
permalink: upgrade/convert-node2-to-drive-shelf.html
sidebar: sidebar
keywords: fas2820, aff a150, aff a220, ndu, nondisruptive, upgrade, node2, node4, reassign, drives
summary: Convert node2 to a drive shelf and connect to node4 before reassigning drives from node2 to node4. 
---
= Convert node2 to a drive shelf and connect to node4
:icons: font
:imagesdir: ../media/

[.lead]
Convert node2 to a drive shelf and connect to node4 before reassigning drives from node2 to node4. Node1 and node2 are the controllers inside the drive shelf.

.Steps
. Disconnect all the network cables from node2.
. Remove node2 from the AFF A150, AFF A220, or FAS2820 chassis.
. Insert the IOM12 or IOM12B module into the bay of node2.
. Cable the node4 serial-attached SCSI (SAS) port to an available port on the IOM12 or IOM12B module. See the link:https://hwu.netapp.com[Hardware Universe^] to verify the SAS ports for your system. 

. Create temporary cluster connections by connecting node1 ports e0a and e0b to any two 25GbE ports on node4.
+
NOTE: If node4 only supports 10GbE cluster connections, you must have 10GbE cabling to create temporary cluster connections.


.What's next?

link:reassign-node2-drives.html[Reassign drives from node2 to node4]

// 2023 Oct 12, AFFFASDOC-64