---
permalink: upgrade/migrate-fas2820-node2-lifs-aggregates.html
sidebar: sidebar
keywords: fas2820, ndu, nondisruptive, upgrade, node1, node2, migrate, aggregates, lifs
summary: Migrate the logical interfaces (LIFs) and data aggregates on FAS2820 node2 to node1 before converting node2 to a drive shelf.
---
= Migrate LIFs and data aggregates on FAS2820 node2 to node1
:icons: font
:imagesdir: ../media/

[.lead]
Migrate the logical interfaces (LIFs) and data aggregates on FAS2820 node2 to node1 before converting node2 to a drive shelf.

.Before you begin
Verify that you meet the following requirements:

* The FAS2820 and replacement controllers have the same ONTAP release and patch version, when possible. Refer to the https://hwu.netapp.com[NetApp Hardware Universe^] for supported ONTAP releases.

[NOTE]
====
* You need to netboot and install the ONTAP version on node3 and node4 to match the ONTAP version on the FAS2820 systems. Node3 and node4 are the replacement controllers.
* Both the primary and backup boot image of the node3 and node4 controllers must have the same ONTAP version.
* You need to clear any residual cluster configuration on node3 and node4 by performing a `wipeconfig` from the boot menu.
====

* Both replacement controllers are on standby at the LOADER prompt.
* All required cabling is available.


.About this task
The following steps are performed on FAS2820 node1.

.Steps
. Access the advanced privilege level:
+
[source,cli]
----
set -privilege advanced
----
. Disable storage failover automatic giveback:
+
[source,cli]
----
storage failover modify -node node1 -auto-giveback false
----
. Disable auto-revert of the LIFs across both nodes of the HA pair:
+
[source,cli]
----
network interface modify -lif * -auto-revert false  
----
. Display the status of all data network LIFs:
+
[source,cli]
----
network interface show -role data
----
. Display the status of the cluster management LIFs:
+
[source,cli]
----
network interface show -role cluster-mgmt
----
. Migrate all data LIFs from the storage virtual machines hosted on node2:
+
[source,cli]
----
network interface migrate -vserver <vserver_name> -lif <lif_name> -destination-node <node1> -destination-port <port_name>
----
+
NOTE: This command only migrates non-SAN LIFs. You cannot use it to migrate iSCSI and FCP LIFs.
. Display the status of all data LIFs in the cluster:
+
[source,cli]
----
network interface show -role data
----
. If any LIFs are down, set their administrative status to `up` by entering the following command once for each LIF:
+
[source,cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> -status-admin up
----
. Display the status of all data aggregates in the cluster:
+
[source,cli]
----
storage aggregate show
----
. Display failover eligibility:
+
[source,cli]
----
storage failover show
----
. Migrate the data aggregates on node2 to node1:
+
[source,cli]
----
storage aggregate relocation start -aggregate <aggregate_name> -node <node2> -destination <node1>  
----
. Display the status of all data aggregates in the cluster:
+
[source,cli]
----
storage aggregate show
----
. Display the status of all data volumes in the cluster:
+
[source,cli]
----
volume show
----
. Display the `ha` status and ownership of epsilon:
+
[source,cli]
----
cluster show 
----

. Disable cluster ha:
+
[source,cli]
----
cluster ha modify -configured false 
----
. Display the `ha` status and ownership of epsilon:
+
[source,cli]
----
cluster show
----
. Halt node2:
+
[source,cli]
----
halt -node <node2> -inhibit-takeover true -ignore-quorum-warnings true
----

.What's next?

link:convert-fas2820-node2-drive-shelf.html[Convert node2 to a drive shelf and connect to node4]

// 2023 Oct 12, AFFFASDOC-64