---
permalink: upgrade/upgrade-remove-original-nodes-move-volumes.html
sidebar: sidebar

keywords: volume, move, node, remove, original, cluster, configuration, disk, initialize, remove the original nodes from the cluster
summary: After the volumes have been moved to the new nodes, you remove the original nodes from the cluster. When you remove a node, the node’s configuration is erased and all disks are initialized.
---
= Remove the original nodes from the cluster
:icons: font
:imagesdir: ../media/

[.lead]
After moving the volumes from the original to the new nodes and moving or deleting data LIFs, you remove the original nodes from the cluster. When you remove a node, the node's configuration is erased and all disks are initialized.

.Steps
. Disable high-availability configuration on the original nodes:
+
`storage failover modify -node <original_node_name> -enabled false`
. Access the advanced privilege level:
+
`set -privilege advanced`
. Identify the node that has epsilon:
+
`cluster show`
+
In the following example, "node0" currently holds epsilon:
+
----
cluster::*>
Node                 Health  Eligibility  Epsilon
-------------------- ------- ------------ ------------
node0                true    true         true
node1                true    true         false
node2                true    true         false
node3                true    true         false
----

. [[epsilon-true]]If one of the original nodes holds epsilon, move epsilon to a node that you are not removing from the cluster:
.. Remove epsilon from the original node:
+
`cluster modify -node <original_node_name> -epsilon false`
.. Assign epsilon to a different node:
+
`cluster modify -node <new_node_name> -epsilon true`
. Identify the current master node:
+
`cluster ring show`
+
The master node is the node that holds processes such as `mgmt`, `vldb`, `vifmgr`, `bcomd`, and `crs`.
. Before removing a node, ensure it's not the current master node. If it is, then enable one of the nodes remaining in the cluster to be elected as master:

.. Make the current master node ineligible to participate in the cluster:
+
`cluster modify -node <original_node_name> -eligibility false`
+
The node is marked unhealthy until eligibility is restored. When the master node becomes ineligible, one of the nodes remaining in the cluster is elected by the cluster quorum as the new master.
+
[NOTE]
====
If you are performing this step on the first node in an HA pair, you should mark only that node as ineligible. Do not modify the status of the HA partner. If the partner node is selected as the new master, you need to verify if it holds epsilon before making it ineligible. This is done when you repeat these steps to remove the partner node.

If a node holds epsilon, move epsilon to a different node before changing the node's eligibility to `eligibility false`, as described in <<epsilon-true,Step 4>>. 
====
.. Make the previous master node eligible to participate in the cluster again:
+
`cluster modify -node <node_name> -eligibility true`

. Log into the remote node management LIF or the cluster-management LIF on a node that is remaining in the cluster.
+
Remove each original node from the cluster (advanced privilege level):
+
[role="tabbed-block"]
====
.ONTAP 9.4 and later
--
With node name:
[source,cli]
----
cluster remove-node -node <original_node_name>
----
With node IP:
[source,cli]
----
cluster remove-node -cluster_ip <original_node_ip>
----
--
.ONTAP 3
--

[source,cli]
----
cluster unjoin
----
--
====
+
If you have a mixed version cluster and you are removing the last lower version node, use the `-skip-last-low-version-node-check` parameter with these commands.
+
The system informs you of the following:

** You must also remove the node's failover partner from the cluster.
** After the node is removed and before it can rejoin a cluster, you must use boot menu option *(4) Clean configuration and initialize all disks* or option *(9) Configure Advanced Drive Partitioning* to erase the node's configuration and initialize all disks.
+
A failure message is generated if you have conditions that you must address before removing the node. For example, the message might indicate that the node has shared resources that you must remove or that the node is in a cluster HA configuration or storage failover configuration that you must disable.
+
If the node is the quorum master, the cluster briefly loses and then returns to quorum. This quorum loss is temporary and does not affect any data operations.

. If a failure message indicates error conditions, address those conditions and rerun the `cluster remove-node` or `cluster unjoin` command.
+
The node automatically reboots after it is successfully removed from the cluster.

. If you are repurposing the node, erase the node configuration and initialize all disks:
.. During the boot process, press Ctrl-C to display the boot menu when prompted to do so.
.. Select the boot menu option *(4) Clean configuration and initialize all disks*.
. Return to admin privilege level:
+
[source,cli]
----
set -privilege admin
----

. Repeat the preceding steps to remove the failover partner from the cluster.

. If the cluster has only two nodes remaining, configure high availability for the two-node cluster:
+
`cluster ha modify -configured true`

.What's next?
link:upgrade-complete-move-volumes.html[Complete the move volumes upgrade]

// 2025 DEC 12, AFFFASDOC-442
// 2022 MAY 13, BURT 1476241 
