---
permalink: upgrade/upgrade-attach-shelves-reassign-disks.html
sidebar: sidebar
keywords: reassign, disk, belong, node1, node2, node3, node4, node, attach, storage, shelves, shelf, reassign, ownership, attach storage shelves reassign disk ownership
summary: You must reassign the disks that belonged to node1 and node2 to node3 and node4 respectively.
---
= Attach storage shelves and reassign disk ownership
:icons: font
:imagesdir: ../media/

[.lead]
You must reassign the disks that belonged to node1 and node2 to node3 and node4 respectively.

.About this task

You perform the steps in this section on node3 and node4. Complete each step on node3 and then node4 before going on to the next step.

.Steps

[[reassign-spare-disks-step1]]
. Connect the storage shelf cables from the shelves that were previously attached:
+
* Connect the node1 cables to node3 
* Connect the node2 cables to node4. 
+
CAUTION: Do not connect new shelves to node3 or node4 during this upgrade procedure. You can nondisruptively connect new shelves to the system after completing the controller upgrade.

. Verify the power supply and physical connectivity of the shelves.

. From the node3 LOADER prompt, boot to Maintenance mode:
+
`boot_ontap maint`

. Display the system ID of node3:
+
`disk show -v`
+
----
*> disk show -v
Local System ID: 101268854
...
----
+
Record the system ID of node3 for use in <<reassign-disks-and-aggregates,Step 5>>.

. [[reassign-disks-and-aggregates]]Reassign the disks and data aggregates:
+
[role="tabbed-block"]
====
.Reassign to node3
--
Reassign node1's spare disks, disks belonging to the root aggregate, and any data aggregates to node3:

`disk reassign -s <node1_sysid> -d <node3_sysid> -p <node4_sysid>`

** The parameter `node1_sysid` is the value you recorded in  _Shutting down the original nodes_, link:upgrade-shutdown-remove-original-nodes.html#shutdown_node_step5[Step 5].
** Specify the parameter `-p <node2_sysid>` only when shared disks are present.
--
.Reassign to node4
--
Reassign node2's spare disks, disks belonging to the root aggregate, and any data aggregates to node4:

`disk reassign -s <node2_sysid> -d <node4_sysid> -p <node3_sysid>`

** The parameter `node2_sysid` is the value you recorded in  _Shutting down the original nodes_, link:upgrade-shutdown-remove-original-nodes.html#shutdown_node_step5[Step 5].
** Specify the parameter `-p <node3_sysid>` only when shared disks are present.
--
====
+
The system displays a message similar to the following:
+
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)?n

After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)?y
----
. Enter `y` to continue.
+
The system displays a message similar to the following:
+
----
The system displays the following message:
Disk ownership will be updated on all disks previously belonging to Filer with sysid
<sysid>.
Do you want to continue (y/n)? y
----

. Enter `y` to continue.
. Confirm that node1's root aggregate is set to `root` in the options field and that other aggregates are online:
+
`aggr status`
+
You should see output similar to the following:
+
----
*> aggr status
           Aggr State           Status                Options
          aggr0 online          raid_dp, aggr         root
                                64-bit
----

. [[reassign-spare-disks-step9]]Exit Maintenance mode:
+
`halt`

. Repeat <<reassign-spare-disks-step1,Step 1>> to <<reassign-spare-disks-step9,Step 9>> on node4.

.What's next?
After attaching storage shelves and reassigning disk ownership, link:upgrade-restore-root-volume-config.html[restore the root volume configuration].

// 2026 JUL 29, ontap-systems-upgrade-issue-168
// 2026 JUL 21, ontap-systems-upgrade-issue-172
// 2026 JUL 21, ontap-systems-upgrade-issue-173
// 2023 NOV 14, ontap-systems-upgrade-issues-94
// Clean-up, 2022-03-09
