---
sidebar: sidebar
permalink: upgrade-arl-auto-app-9151/decide_to_use_the_aggregate_relocation_guide.html
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability
summary: "Decide whether to use ARL to upgrade controllers running ONTAP 9.8 or later by using `system controller replace` commands."
---
= Decide whether to use the aggregate relocation procedure
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
This content describes how to upgrade the storage controllers in an HA pair with new controllers while keeping the existing data and disks. This is a complex procedure that should be used only by experienced administrators.

You can use this content under the following circumstances:

* You are running ONTAP 9.15.1 or later.
* You do not want to add the new controllers as a new HA pair to the cluster and migrate the data using the volume move procedure.
* You are experienced in administering ONTAP and are comfortable with the risks of working in the diagnostic privilege mode.

NOTE: You can use NetApp Storage Encryption (NSE), NetApp Volume Encryption (NVE), and NetApp Aggregate Encryption (NAE) with this procedure.

[[sys_commands_9151_supported_systems]]The following table shows the supported model matrix for the controller upgrade.

|===
|Existing controller |Replacement controller

|AFF A300
|AFF A70, AFF A90, and AFF A1K

|AFF A400
|AFF A70, AFF A90, and AFF A1K

|AFF A700
|AFF A70, AFF A90, and AFF A1K

|AFF A900
|AFF A90 and AFF A1K

|===

[NOTE]
====
The AFF A70 and AFF A90 are integrated systems with onboard disks. The two controllers and disks are in a single chassis. You cannot upgrade an existing system if the new controllers have internal drives.

To upgrade an AFF A800 to an AFF A70 or AFF A90, see link:../upgrade-arl-auto-affa900/index.html[Use "system controller replace" commands to upgrade controller models in the same chassis].

If your controller upgrade model combination is not in the above table, contact technical support.
====

include::../_include/ru_auto_decide_use_arl_guide_end.adoc[]
