---
sidebar: sidebar
permalink: upgrade-arl-auto-app-9151/decide_to_use_the_aggregate_relocation_guide.html
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability
summary: "Decide whether to use ARL to upgrade controllers running ONTAP 9.15.1 or later by using `system controller replace` commands."
---
= Decide whether to use the aggregate relocation procedure
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
This procedure describes how to upgrade the storage controllers in an HA pair with new controllers while keeping the existing data and disks. This is a complex procedure that should be used only by experienced administrators.

You can use this procedure under the following circumstances:

* You are running ONTAP 9.15.1 or later.
* You do not want to add the new controllers as a new HA pair to the cluster and migrate the data using the volume move procedure.
* You are experienced in administering ONTAP and are comfortable with the risks of working in the diagnostic privilege mode.

NOTE: You can use NetApp Storage Encryption (NSE), NetApp Volume Encryption (NVE), and NetApp Aggregate Encryption (NAE) with this procedure.

You cannot use this procedure under the following circumstances:

* You are upgrading an AFF A800 to an AFF A70 or AFF A90. To perform this AFF A800 upgrade, see link:other_references.html[References] to link to _Use "system controller replace" commands to upgrade controller models in the same chassis_.
* You are upgrading a V-Series system or FlexArray Virtualization storage system using an external array for backend storage. Contact technical support for options to upgrade a V-series or FlexArray system.
* You are upgrading a MetroCluster FC or IP configuration. To upgrade a MetroCluster configuration, see link:other_references.html[References] to link to the _MetroCluster Upgrade and Expansion documentation_.

[[sys_commands_9151_supported_systems]]The following table shows the supported model matrix for the controller upgrade.

|===
|Existing controller |Replacement controller

|AFF A300
|AFF A70, AFF A90, and AFF A1K

|AFF A400
|AFF A70, AFF A90, and AFF A1K

|AFF A700
|AFF A70, AFF A90, and AFF A1K

|AFF A900
|AFF A90 and AFF A1K

|===

[NOTE]
====
The AFF A70 and AFF A90 are integrated systems with two onboard disks and two controllers in a single chassis. 

* If you are upgrading to an AFF A70 or AFF A90 with internal drives, you must remove ownership of these drives before you upgrade. After completing the upgrade, you can assign the internal drives to the AFF A70 or AFF A90 nodes and use them for creating data aggregates. It is not mandatory to migrate root or data aggregates to internal drives.
* If you are upgrading to an AFF A70 or AFF A90 without internal drives, you don't need to assign internal drives after completing the upgrade.  

If your controller upgrade model combination is not in the above table, contact technical support.
====

include::../_include/ru_auto_decide_use_arl_guide_end.adoc[]

// 2024 SEP 25, AFFFASDOC-265