---
sidebar: sidebar
permalink: upgrade-arl-auto-app-9151/guidelines_for_upgrading_controllers_with_arl.html
keywords: guidelines, upgrading, controllers, ARL
summary: "Understand if you can upgrade controllers running ONTAP 9.8 or later by using `system controller replace` commands."
---
= Guidelines for upgrading controllers with ARL
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
To understand whether you can use ARL to upgrade a pair of controllers running ONTAP 9.15.1 or later depends on the platform and the configuration of both the original and replacement controllers.

== Supported upgrades for ARL

When you upgrade a pair of nodes using this ARL procedure for ONTAP 9.8 or later, you must verify that ARL can be performed on the original and replacement controllers.

You must check the size of all defined aggregates and number of disks supported by the original system. You must then compare the aggregate sizes and number of disks supported to the aggregate size and number of disks supported by the new system.  Refer to link:other_references.html[References] to link to the _Hardware Universe_ where this information is available. The aggregate size and the number of disks supported by the new system must be equal to or greater than the aggregate size and number of disks supported by the original system.

You must validate in the cluster mixing rules whether new nodes can become part of the cluster with the existing nodes when the original controller is replaced. For more information about cluster mixing rules, refer to link:other_references.html[References] to link to the _Hardware Universe_.

If you have a system with more than two cluster ports per node, such as an AFF 700, and the system is using the cluster interconnect card in slot4 in breakout mode to create ports e4a, e4b, e4c, and e4d and ports e4e, e4f, e4g, and e4h, you must migrate and re-home the cluster LIFs to two cluster ports per node before you start the upgrade. If you perform the controller upgrade with more than two cluster ports per node, cluster LIFs might be missing on the new controller after the upgrade.

Controller upgrade using ARL is supported on systems configured with SnapLock Enterprise and SnapLock Compliance volumes.

== Two-node switchless clusters

If you are upgrading nodes in a two-node switchless cluster, you can leave the nodes in the switchless cluster while performing the upgrade. You do not need to convert them to a switched cluster.

== Upgrades not supported for ARL

You cannot upgrade replacement controllers that do not support the disk shelves connected to the original controllers

Refer to link:other_references.html[References] to link to the _Hardware Universe_ for disk-support information.

If you want to upgrade entry level controllers with internal drives, refer to link:other_references.html[References] to link to _Upgrade by moving volumes or storage_ and go to the procedure _Upgrading a pair of nodes running clustered Data ONTAP by moving volumes_.

== Troubleshoot

If any problems occur while upgrading the controllers, see link:troubleshoot_index.html[Troubleshoot] for more information and possible solutions.

If you do not find a solution to the problem you encountered, contact technical support.
