== Configure FC ports on node4

If node4 has FC ports, either onboard or on an add-on FC adapter, you must set port configurations on the node before you bring it into service because the ports are not preconfigured when the systems are shipped. If you don't configure the ports as required, you might experience a disruption in service.

.Before you begin

You must have the values of the FC port settings from node2 that you saved in the section link:prepare_nodes_for_upgrade.html[Prepare the nodes for upgrade].

.About this task

You can skip this section if your system does not have FC configurations. If your system has onboard UTA/UTA2 ports or a UTA/UTA2 adapter, you configure them in <<Check and configure UTA/UTA2 ports on node4>>.

IMPORTANT: Enter the commands in this section at the Maintenance mode shell prompt.

.Steps

. Display information about all FC and converged network adapters on the system:
+ 
`system node hardware unified-connect show`

. Compare the FC settings on node4 with the settings that you captured earlier from node1.
. Modify the FC ports on node4 as needed:
+
* To program as target ports:
+
`ucadmin modify -m fc -t target _adapter_`
+
For example: `ucadmin modify -m fc -t target 2a`
* To program initiator ports:
+
`ucadmin modify -m fc -t initiator _adapter_`
+
`-t` is the FC4 type: target or initiator.
+
For example: `ucadmin modify -m fc -t initator 2b`
. Halt the node:
+
`halt`

. Boot the system from LOADER prompt:
+
`boot_ontap menu`

. After you enter the command, wait until the system stops at the boot environment prompt.
. Select option `5` from the boot menu for maintenance mode.
