== Configure FC ports on node3

If node3 has FC ports, either onboard or on an add-on FC adapter, you must set port configurations on the node before you bring it into service because the ports are not preconfigured when the systems are shipped. If you don't configure the ports, you might experience a disruption in service.

.Before you begin

You must have the values of the FC port settings from node1 that you saved in the section link:prepare_nodes_for_upgrade.html[Prepare the nodes for upgrade].

.About this task

You can skip this section if your system does not have FC configurations. If your system has onboard UTA/UTA2 ports or a UTA/UTA2 card, you configure them in <<Check and configure UTA/UTA2 ports on node3>>.

IMPORTANT: Enter the commands in this section at the Maintenance mode shell prompt.

.Steps

. Compare the FC settings on node3 with the settings that you captured earlier from node1.
. Take one of the following actions to modify the FC ports on node3, as needed:
+
In Maintenance mode (option 5 at boot menu):
+
* To program as target ports:
+
`ucadmin modify -m fc -t target <adapter>`
+
For example: `ucadmin modify -m fc -t target 2a`
* To program initiator ports:
+
`ucadmin modify -m fc -t initiator <adapter>`
+
For example: `ucadmin modify -m fc -t initator 2b`

. Verify the new settings by using the following command and examining the output:
+
`ucadmin show`

. Halt the node:
+
`halt`

. Boot the system from LOADER prompt:
+
`boot_ontap menu`

. After you enter the command, wait until the system stops at the boot environment prompt.

. Select option `5` from the boot menu for maintenance mode.
