== Step 2: Correct aggregate ownership if an ARL precheck fails

If the Aggregate Status Check fails, you must return aggregates owned by the partner node to the home owner node and initiate the precheck process again.

.Steps

. Return the aggregates currently owned by the partner node to the home owner node:
+
`storage aggregate relocation start -node _source_node_ -destination _destination-node_ -aggregate-list *`

. Verify that neither node1 nor node2 still owns aggregates for which it is the current owner (but not the home owner):
+
`storage aggregate show -nodes _node_name_ -is-home false -fields owner-name, home-name, state`
+
The following example shows the output of the command when a node is both the current owner and home owner of aggregates:
+
----
cluster::> storage aggregate show -nodes node1 -is-home true -fields owner-name,home-name,state
aggregate   home-name  owner-name  state
---------   ---------  ----------  ------
aggr1       node1      node1       online
aggr2       node1      node1       online
aggr3       node1      node1       online
aggr4       node1      node1       online

4 entries were displayed.
----

. Restart the controller replacement process:

`system controller replace start -nodes _node_names_`

// BURT 1476241, 2022-05-11
