[[uta-ports-node3]]
== Check and configure UTA/UTA2 ports on node3

If node3 has onboard UTA/UTA2 ports or a UTA/UTA2 card, you must check the configuration of the ports and possibly reconfigure them, depending on how you want to use the upgraded system.

.Before you begin

You must have the correct SFP+ modules for the UTA/UTA2 ports.

.About this task

If you want to use a Unified Target Adapter (UTA/UTA2) port for FC, you must first verify how the port is configured.

NOTE: NetApp marketing materials might use the term UTA2 to refer to CNA adapters and ports. However, the CLI uses the term CNA.

You can use the `ucadmin show` command to verify the current port configuration:

----
*> ucadmin show
          Current  Current    Pending  Pending    Admin
 Adapter  Mode     Type       Mode     Type       Status
 -------  -------  ---------  -------  ---------  -----------
 0e       fc       target     -        initiator  offline
 0f       fc       target     -        initiator  offline
 0g       fc       target     -        initiator  offline
 0h       fc       target     -        initiator  offline
 1a       fc       target     -        -          online
 1b       fc       target     -        -          online
6 entries were displayed.
----

UTA/UTA2 ports can be configured into native FC mode or UTA/UTA2 mode. FC mode supports FC initiator and FC target; UTA/UTA2 mode enables concurrent NIC and FCoE traffic sharing the same 10GbE SFP+ interface and supports FC targets.

UTA/UTA2 ports might be found on an adapter or on the controller, and have the following configurations, but you should check the configuration of the UTA/UTA2 ports on the node3 and change it, if necessary:

* UTA/UTA2 cards ordered when the controller is ordered are configured before shipment to have the personality you request.
* UTA/UTA2 cards ordered separately from the controller are shipped with the default FC target personality.
* Onboard UTA/UTA2 ports on new controllers are configured before shipment to have the personality you request.
+
NOTE: Enter the commands in this section at the cluster prompt unless directed to enter maintenance mode.

.Steps

. Check how the ports are currently configured entering the following command on node3:
+
`system node hardware unified-connect show`
+
The system displays output similar to the following example:
+
----
 cluster1::> system node hardware unified-connect show

                Current  Current    Pending  Pending  Admin
 Node  Adapter  Mode     Type       Mode     Type     Status
 ----  -------  -------  ---------  -------  -------  ------
 f-a   0e       fc       initiator  -        -        online
 f-a   0f       fc       initiator  -        -        online
 f-a   0g       cna      target     -        -        online
 f-a   0h       cna      target     -        -        online
 f-b   0e       fc       initiator  -        -        online
 f-b   0f       fc       initiator  -        -        online
 f-b   0g       cna      target     -        -        online
 f-b   0h       cna      target     -        -        online
 12 entries were displayed.
----

. [[step2]]If the current SFP+ module does not match the desired use, replace it with the correct SFP+ module.
+
Contact your NetApp representative to obtain the correct SFP+ module.

. [[step3]]Examine the output of the `system node hardware unified-connect show` or `ucadmin show` command to determine whether the UTA/UTA2 ports have the personality you want.

. [[step4]]Take one of the following actions:
+
[cols="35,65"]
|===
|If the UTA/UTA2 ports... |Then...

|Do not have the personality that you want
|Go to <<man_check_3_step5,Step 5>>.
|Have the personality that you want
|Skip Step 5 through Step 12 and go to <<man_check_3_step13,Step 13>>.
|===

. [[man_check_3_step5]]If the system has storage disks and is running clustered Data ONTAP 8.3, boot node3 and enter maintenance mode:
+
`boot_ontap maint`

. [[man_check_3_step6]]Take one of the following actions:
+
[cols="35,65"]
|===
|If you are configuring... |Then...

|Ports on a UTA/UTA2 card
|Go to <<man_check_3_step7,Step 7>>.
|Onboard UTA/UTA2 ports
|Skip Step 7 and go to <<man_check_3_step8,Step 8>>.
|===

. [[man_check_3_step7]]If the adapter is in initiator mode, and if the UTA/UTA2 port is online, take the UTA/UTA2 port offline:
+
`storage disable adapter _adapter_name_`
+
Adapters in target mode are automatically offline in maintenance mode.

. [[man_check_3_step8]]If the current configuration does not match the desired use, change the configuration as needed:
+
`ucadmin modify -m fc|cna -t initiator|target _adapter_name_`
+
* `-m` is the personality mode, `fc` or `cna`.
* `-t` is the FC4 type, `target` or `initiator`.
+
NOTE: You need to use the FC initiator for tape drives and MetroCluster configurations. You need to use the FC target for SAN clients.

. Verify the settings:
+
`ucadmin show`

. Verify the settings:
+
.. Stop the system:
+
`halt`
+
The system stops at the boot environment prompt.
+
.. Enter the following command:
+
`boot_ontap`

. [[step11]]Verify the settings:
+
`system node hardware unified-connect show`
+
The output in the following examples show that the FC4 type of adapter "1b" is changing to `initiator` and that the mode of adapters "2a" and "2b" is changing to `cna`:
+
----
 cluster1::> system node hardware unified-connect show

                Current  Current    Pending  Pending      Admin
 Node  Adapter  Mode     Type       Mode     Type         Status
 ----  -------  -------  ---------  -------  -----------  ------
 f-a   1a       fc       initiator  -        -            online
 f-a   1b       fc       target     -        initiator    online
 f-a   2a       fc       target     cna      -            online
 f-a   2b       fc       target     cna      -            online

 4 entries were displayed.
----

. [[step12a]]Place any target ports online by entering the following command, once for each port:
+
`network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -state up`

. [[man_check_3_step13]]Cable the port.

// Clean-up, 2022-03-09
