You must install node4 in the rack, transfer node2 connections to node4, and boot node4. You must also reassign any node2 spares, any disks belonging to root, and any non-root aggregates that were not relocated to node3 earlier.

.About this task

You must netboot node4 if it doesn't have the same version of ONTAP 9 that is installed on node2. After you install node4, boot it from the ONTAP 9 image stored on the web server. You can then download the correct files to the boot media device for subsequent system boots by following the instructions in link:prepare_for_netboot.html[Prepare for netboot].

However, you aren't required to netboot node4 if it has the same or later version of ONTAP 9 that is installed on node2.


[IMPORTANT]
====
* For an AFF A800 or AFF C800 controller upgrade, you must ensure that all drives in the chassis are firmly seated against the midplane before removing node2. For more information, see link:../upgrade-arl-auto-affa900/replace-node1-affa800.html[Replace the AFF A800 or AFF C800 controller modules]. 

* If you're upgrading a system with storage disks, you must complete this entire section and then proceed to the section link:set_fc_uta_uta2_config_node4.html[Set the FC or UTA/UTA2 configuration on node4], entering commands at the cluster prompt.
====

.Steps

. [[man_install4_Step1]]Take one of the following actions:
+
[cols=2*,options="header",cols="35,65"]
|===
|If node4 will be in ... |Then...
|A chassis separate from node3 |Go to <<man_install4_Step2,Step 2>>.
|The same chassis with node3 |Skip Steps 2 and 3 and go to <<man_install4_Step4,Step 4>>.
|===

. [[man_install4_Step2]] Make sure that node4 has sufficient rack space.
+
If node4 is in a separate chassis from node3, you can put node4 in the same location as node2. If node3 and node4 are in the same chassis, then node4 is already in its appropriate rack location.

. Install node4 in the rack, following the instructions in the _Installation and Setup Instructions_ for the node model.

. [[man_install4_Step4]]Cable node4, moving the connections from node2 to node4.
+
The following references help you make proper cable connections. Go to link:other_references.html[References] to link to them.
+
* _Installation and Setup Instructions_ for the node4 platform
* The appropriate disk shelf procedure
* The _HA pair management_ documentation

+
Cable the following connections:

* Console (remote management port)
* Cluster ports
* Data ports
* Cluster and node management ports
* Storage
* SAN configurations: iSCSI Ethernet and FC switch ports

+
NOTE: You do not need to move the interconnect card/FC_VI card or interconnect/FC_VI cable connection from node2 to node4 because most platform models have unique interconnect card models.

. Take one of the following actions:
+
[cols=2*,options="header",cols="35,65"]
|===
|If node4 is in... |Then...
|The same chassis as node3 |Go to <<man_install4_Step8,Step 8>>.
|A chassis separate from node3 |Go to <<man_install4_Step6,Step 6>>.
|===

. [[man_install4_Step6]]Turn on the power to node4, and then interrupt the boot by pressing Ctrl-C to access the boot environment prompt.
+
NOTE: When you boot node4, you might see the following message:

+
----
WARNING: The battery is unfit to retain data during a power
         outage. This is likely because the battery is
         discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will
         complete and services will be engaged.
         To override this delay, press 'c' followed by 'Enter'
----

. [[man_install4_Step7]]If you see the warning message in Step 6, take the following actions:
.. Check for any console messages that might indicate a problem other than a low NVRAM battery and, if necessary, take any required corrective action.
.. Allow the battery to charge and the boot process to finish.
+
WARNING: *Warning: Do not override the delay. Failure to allow the battery to charge could result in a loss of data.*

. [[man_install4_Step8]]At the Maintenance mode prompt, enter the following command:
+
`halt`
+
The system stops at the boot environment prompt.
. Configure node4 for ONTAP:
+
`set-defaults`
// 2025 MAY 22, AFFFASDOC-329
// 2022 APR 17, ontap-systems-upgrade-issues-64/BURT 1519747