== Configure FC ports on node4

If node4 has FC ports, either onboard or on an FC adapter, you must set port configurations on the node before you bring it into service because the ports are not preconfigured. If the ports are not configured, you might experience a disruption in service.

.Before you begin

You must have the values of the FC port settings from node2 that you saved in the section link:prepare_nodes_for_upgrade.html[Prepare the nodes for upgrade].

.About this task

You can skip this section if your system does not have FC configurations. If your system has onboard UTA/UTA2 ports or a UTA/UTA2 adapter, you configure them in <<Check and configure UTA/UTA2 ports on node4>>.

IMPORTANT: Enter the commands in this section at the cluster prompt. 

.Steps

. Display information about all FC and converged network adapters on the system:
+
`system node hardware unified-connect show`

. Compare the FC settings on the new nodes with the settings that you captured earlier from the original node.

. Modify the FC ports on node4 as needed:
+
* To program target ports:
+
`system node hardware unified-connect modify -type \| -t target -adapter _port_name_`
+
* To program initiator ports:
+
`system node unified-connect modify type \| -t initiator -adapter _port_name_`
+
`-type` is the FC4 type, target or initiator.

. Verify the new settings by entering the following command and examining the output:
+
`system node unified-connect show`

. Take one of the following actions:
+
[cols=2*,options="header",cols="35,65"]
|===
|If the default FC settings on the new nodes are... |Then…
|The same as the ones you that captured on the original nodes
|Go to <<man_config_4_Step9,Step 9>>.
|Different from the ones that you captured on the original nodes
|Go to <<man_config_4_Step6,Step6>>.
|===

. [[man_config_4_Step6]]Exit Maintenance mode:
+
`halt`

. After you enter the command, wait until the system stops at the boot environment prompt.

. Boot node4 by entering the following command at the boot environment prompt:
+
`boot_ontap`

. [[man_config_4_Step9]]Take one of the following actions:
+
* Go to <<Check and configure UTA/UTA2 ports on node4>> if node4 has a UTA/UTA2A card or UTA/UTA2 onboard ports.
+
* Skip the section and go to link:map_ports_node2_node4.html[Map ports from node2 to node4] if node4 does not have a UTA/UTA2 card or UTA/UTA2 onboard ports.


// BURT 1478241, 2022-05-13
