== Configure FC ports on node3

If node3 has FC ports, either onboard or on an FC adapter, you must set port configurations on the node before you bring it into service because the ports are not preconfigured. If the ports are not configured, you might experience a disruption in service.

.Before you begin

You must have the values of the FC port settings from node1 that you saved in link:prepare_nodes_for_upgrade.html[Prepare the nodes for upgrade].

.About this task

You can skip this section if your system does not have FC configurations. If your system has onboard UTA/UTA2 ports or a UTA/UTA2 card, you configure them in <<Check and configure UTA/UTA2 ports on node3>>.

IMPORTANT: If your system has storage disks, enter the commands in this section at the cluster prompt.

.Steps

. Display information about all FC and converged network adapters on the system.
+
`system node hardware unified-connect show`

. Compare the FC settings of node3 with the settings that you captured earlier from node1.

. [[man_config_3_step3]]Take one of the following actions:
+
[cols="35,65"]
|===
|If the default FC settings on the new nodes are... |Then...

|The same as the ones you that captured on node1
|Go to <<man_config_3_step11,Step 11>>.
|Different from the ones that you captured on node1
|Go to <<man_config_3_step6,Step 6>>.
|===

. [[man_config_3_step4]]Modify the FC ports on node3 as needed by entering one of the following commands:
+
* To program target ports:
+
`system node hardware unified-connect modify -type \| -t target -adapter _port_name_`
+
* To program initiator ports:
+
`system node hardware unified-connect modify -type \| -t initiator -adapter _port_name_`
+
`-t` is the FC4 type: target or initiator.

. Verify the new settings by entering the following command and examining the output:
+
`system node hardware unified-connect show`

. Exit maintenance mode by entering the following command:
+
`halt`

. [After you enter the command, wait until the system stops at the boot environment prompt.

. Boot node3 at the boot environment prompt:
+
`boot_ontap`

. [[man_config_3_step11]]Take one of the following actions:
+
* If node3 has a UTA/UTA2 card or UTA/UTA2 onboard ports, go to <<Check and configure UTA/UTA2 ports on node3>>.
+
* If node3 does not have a UTA/UTA2 card or UTA/UTA2 onboard ports, skip <<Check and configure UTA/UTA2 ports on node3>> and go to link:map_ports_node1_node3.html[Map ports from node1 to node3].

//22 FEB 2021:  Formatted from CMS
// BURT 1478241, 2022-05-13
