---
sidebar: sidebar
permalink: upgrade-arl-manual/index.html
keywords:  controller, aggregate, relocation, flexarray, manual, upgrade, metrocluster
summary: "Use the manual ARL upgrade procedure to upgrade controller hardware running ONTAP 9.7 or earlier, relocating the ownership of non-root aggregates."
---
= Learn about this ARL upgrade procedure
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
This procedure describes how to upgrade the controller hardware using manual aggregate relocation (ARL) on systems running ONTAP 9.7 or earlier.

You can use this ARL procedure if you are performing one of the following upgrades:

* FAS system to FAS system
* FAS system to a system with FlexArray Virtualization Software or a V-Series system
* AFF system to AFF system
* System with FlexArray Virtualization Software or a V-Series system to a FAS system, provided that the system with FlexArray Virtualization Software or V-Series system has no array LUNs.
* V-Series system to a system with FlexArray Virtualization Software or a V-Series system

include::../_include/ru_man_use_arl_overview.adoc[]

* This procedure applies to MetroCluster four-node and eight-node configurations running ONTAP 9.5 and earlier. For MetroCluster configurations running ONTAP 9.6 and later, go to link:other_references.html[References] to link to _Using "system controller replace" Commands to Upgrade Controller Hardware Running ONTAP 9.5 to ONTAP 9.7_.


// 24 FEB 2021:  formatted from CMS
