---
sidebar: sidebar
permalink: upgrade-arl-auto-affa900/index.html
keywords: aggregate, relocation, controller, hardware, aggregates, flexarray, metrocluster, terminology, old, system, chassis, disk, disks
summary: "You can upgrade controller hardware by converting an old system to a replacement system, keeping the old system chassis and disks."
---
= Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can nondisruptively upgrade controller hardware on a HA pair by using aggregate relocation (ARL) and converting the existing system to the replacement system, keeping the existing system chassis and disks.

WARNING: This procedure strictly applies to the following upgrade configurations. Do *not* use this procedure to perform an upgrade between any other system combinations.

[cols=3*,options="header",cols="20,20,40"]
|===
|Existing system |Replacement system |Supported ONTAP versions
|AFF A800 ^1^
|AFF A90 or AFF A70
|9.15.1
|AFF A220 configured as an All SAN Array (ASA) 
|ASA A150
|9.13.1P1 and later
|AFF A220
|AFF A150
|9.10.1P15, 9.11.1P11, 9.12.1P5 and later
|AFF A200 
|AFF A150
a|9.10.1P15, 9.11.1P11 and later ^2^


|AFF C190
|AFF A150
|9.10.1P15, 9.11.1P11, 9.12.1P5 and later 

|FAS2620 
|FAS2820
a|9.11.1P7 (FAS2620) ^2^

9.13.1 and later (FAS2820)
|FAS2720 |FAS2820	
|9.13.1 and later
|AFF A700 configured as an ASA 
|ASA A900
|9.13.1P1 and later
|AFF A700 
|AFF A900
|9.10.1P10, 9.11.1P6 and later
|FAS9000 |FAS9500
|9.10.1P10, 9.11.1P6 and later
|===

^1^ When you upgrade to a system introduced in ONTAP 9.15.1, ONTAP converts the storage efficiency of all existing thin-provisioned volumes, including those not using storage efficiency, and applies the new storage efficiency features that make use of the hardware offload functionality. This is an automatic background process, with no visible performance impact to the system. https://docs.netapp.com/us-en/ontap/concepts/builtin-storage-efficiency-concept.html[Learn more^].

^2^ The AFF A200 and FAS2620 systems do not support ONTAP versions later than 9.11.1.

[NOTE]
====
NetApp recommends, when possible, that you have the same ONTAP version on the old and the replacement system.

The minimum ONTAP versions in the preceding table are mandatory. These ONTAP versions have the Service Processor or baseboard management controller (BMC) firmware version that is required to support mixing controller types within a chassis during an upgrade. 
====

During the procedure, you migrate the non-root aggregates between the old controller nodes. After installation, you then migrate the non-root aggregates from the old controller nodes to the replacement controller nodes. The data hosted on the nodes that you are upgrading is accessible during the upgrade procedure.

.About this task
During this controller upgrade procedure, you perform one of the following upgrades:

[cols=2*,options="header",cols="30,70"]
|===
|On the existing... |Perform the following...
|AFF A800
|Swap the two AFF A800 controllers, NVRAM, and all I/O modules with the new controllers and I/O modules.
|AFF A220, AFF A200, AFF C190, FAS2620, or FAS2720
|Swap the controller module on each node on the old controller with the new module. ^1^ 
|AFF A700 or FAS9000
|Swap the controller and NVRAM modules on each node on the old controller with the new modules. ^1^
|===

^1^ You do not need to move, disconnect, or reconnect the I/O cards, data cables, disk shelves, and disks.

This procedure uses a method called aggregate relocation (ARL). ARL takes advantage of the HA configuration and cluster interconnect communication, which enables you to move ownership of non-root aggregates from one node to another if they share storage within the same cluster.

During the procedure, you upgrade the original controller hardware with the replacement controller hardware, relocating the ownership of non-root aggregates. You migrate aggregates multiple times from node to node to confirm that at least one node is serving data from the aggregates throughout the upgrade procedure. You also migrate data LIFs between nodes in the cluster as you proceed.

NOTE: The terms *node1* and *node2*, are used only as a reference to node names in this document. When following the procedure, you must substitute the actual names of your nodes.

.Important information

* This procedure is complex and assumes that you have advanced ONTAP administration skills. You also should read and understand the link:guidelines_for_upgrading_controllers_with_arl.html[Guidelines for upgrading controllers] and the  link:overview_of_the_arl_upgrade.html[Overview of the ARL upgrade] sections before beginning the upgrade.
* This procedure assumes that the replacement controller hardware is new and has not been used in another system. The steps required to prepare used controllers with the `wipeconfig` command are not included in this procedure. You must contact technical support if the replacement controller hardware was previously used as part of another ONTAP cluster or as a standalone single node system.
* You can use this procedure to upgrade the controller hardware in clusters with more than two nodes; however, you need to perform the procedure separately for each HA pair in the cluster.
* If you have a switch that is not supported by the ONTAP version and the replacement system that you are upgrading to, refer to link:other_references.html[References] to link to the _Hardware Universe_.
* The AFF A70 and AFF A90 systems share 100GbE network ports for both cluster and HA connections. These systems can support 10GbE or 25GbE cluster connections to legacy cluster switches; however, NetApp recommends updating to 100GbE cluster speeds when the 10GbE and 25GbE switches are no longer required. For more information, see the following Knowledge Base articles:
+
--
** link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_convert_an_existing_cluster_from_10G_or_25G_cluster_ports_to_40G_or_100G_cluster_ports_on_an_AFF_A1K_AFF_A90_or_AFF_A70[How to convert an existing cluster from 10G or 25G cluster ports to 40G or 100G cluster ports on an AFF A1K, AFF A90 or AFF A70^]
** link:https://kb.netapp.com/?title=on-prem%2Fontap%2FOHW%2FOHW-KBs%2FHow_to_configure_10G_or_25G_cluster_ports_on_a_new_cluster_setup_on_AFF_A1K%252C_AFF_A90_or_AFF_A70[How to configure 10G or 25G cluster ports on a new cluster setup on AFF A1K, AFF A90 or AFF A70^]
--
+
If you cannot link up e0a or e0b cluster ports on the existing node to the cluster ports on the new node, see link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-166978[NetApp Bugs Online Bug ID CONTAP-166978^].
* This procedure only applies to AFF A800, AFF A200, AFF A220, AFF C190, FAS2620, FAS2720, AFF A700, and FAS9000 systems. For all other controller models that need upgrading to an AFF A90, AFF A70, AFF A150, FAS2820, AFF A900, or FAS9500 system, refer to link:other_references.html[References] to link to the _Use "system controller replace" commands to upgrade controller hardware running ONTAP 9.8 or later_ and the _Using aggregate relocation to manually upgrade controller hardware running ONTAP 9.8 or later_ content.
* The ASA A900, AFF A900, and FAS9500 systems only support high-line power (200V to 240V). If your AFF A700 or FAS9000 system is running on low-line power (100V to 120V), you must convert the AFF A700 or FAS9000 input power before using this procedure.
* If you are upgrading from an AFF A800, AFF A200, AFF A220, AFF C190, FAS2620, FAS2720, AFF A700, or FAS9000 system with downtime, you can upgrade controller hardware by moving storage or contact technical support. Refer to link:other_references.html[References] to link to _Upgrade by moving volumes or storage_.

== Automate the controller upgrade process
This procedure provides the steps for the automated procedure, which uses automatic disk assignment and network port reachability checks to simplify the controller upgrade experience.

// 2024 APR 16, AFFFASDOC-32
// 2023 AUG 29, AFFFASDOC-78
// 2023 MAY 29, AFFFASDOC-39
// 2023 MAY 22, BURT 1542232
// 2023 MAY 22, BURT 1531220
// 2022 JAN 30, BURT 1523106
// 2022 APR 26, BURT 1452254
