---
sidebar: sidebar
permalink: upgrade-arl-auto-affa900/stage_7_index.html
keywords: upgrade, authentication, storage, volume, aggregate, encryption, overview, stage 7
summary: "Stage 7 process sequence for an ARL upgrade using `system controller replace` commands to upgrade controller models in the same chassis."
---
= Stage 7 overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
During Stage 7, you confirm that the new nodes are set up correctly and, if the new nodes are encryption-enabled, you configure and set up Storage Encryption or NetApp Volume Encryption. You should also decommission the old nodes and resume the SnapMirror operations.

.Steps

. link:manage-authentication-using-kmip-servers.html[Manage authentication using KMIP servers]
. link:ensure_new_controllers_are_set_up_correctly.html[Confirm that the new controllers are set up correctly]
. link:set_up_storage_encryption_new_module.html[Set up Storage Encryption on the new controller module]
. link:set_up_netapp_volume_encryption_new_module.html[Set up NetApp Volume or Aggregate Encryption on the new controller module]
. link:decommission_old_system.html[Decommission the old system]
. link:resume_snapmirror_operations.html[Resume SnapMirror operations]

[NOTE]
====
The AFF A30, AFF A50, AFF A70, AFF A90, AFF A1K, AFF C30, AFF C60, AFF C80, FAS70, and FAS90 systems share 100GbE network ports for both cluster and HA connections. These systems can support 10GbE or 25GbE cluster connections to legacy cluster switches; however, NetApp recommends updating to 100GbE cluster speeds when the 10GbE and 25GbE switches are no longer required. For more information, see the following Knowledge Base articles:

* link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_configure_10G_or_25G_cluster_ports_on_a_new_cluster_setup[How to configure 10G or 25G cluster ports on a new cluster setup^]
* link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_convert_existing_10G_or_25G_cluster_ports_to_40G_or_100G_cluster_ports[How to convert existing 10G or 25G cluster ports to 40G or 100G cluster ports^]

If you cannot link up e0a or e0b cluster ports on the existing node to the cluster ports on the new node, see link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-166978[NetApp Bugs Online Bug ID CONTAP-166978^].
====

// 2024 SEP 25, AFFFASDOC-268
// 2023 APR 17, ontap-systems-upgrade-issue-64/BURT 1519747
//BURT-1476241 13-Sep-2022
