---
sidebar: sidebar
permalink: upgrade-arl-auto-affa900/stage_6_index.html
keywords: upgrade, boot, node2, verify, restore, overview, stage 1
summary: "Stage 6 process sequence for an ARL upgrade using `system controller replace` commands to upgrade controller models in the same chassis."
---
= Stage 6 overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
During Stage 6, you boot node2 with upgraded system modules and verify the upgraded node2 installation. If you are using NetApp Volume Encryption (NVE), you restore key-manager configuration. You also relocate node1 non-root aggregates and NAS data LIFs from node1 to the upgraded node2 and verify that the SAN LIFs exist on node2.

. link:boot_node2_with_a900_controller_and_nvs.html[Boot node2 with the replacement system modules]
. link:verify_node2_installation.html[Verify the node2 installation]
. link:restore_key_manager_config_node2.html[Restore key-manager configuration on node2]
. link:move_non_root_aggr_and_nas_data_lifs_back_to_node2.html[Move non-root aggregates and NAS data LIFs back to node2]

[NOTE]
====
The AFF A70 and AFF A90 systems share 100GbE network ports for both cluster and HA connections. These systems can support 10GbE or 25GbE cluster connections to legacy cluster switches; however, NetApp recommends updating to 100GbE cluster speeds when the 10GbE and 25GbE switches are no longer required. For more information, see the following Knowledge Base articles:

* link:https://kb.netapp.com/?title=on-prem%2Fontap%2FOHW%2FOHW-KBs%2FHow_to_configure_10G_or_25G_cluster_ports_on_a_new_cluster_setup_on_AFF_A1K%252C_AFF_A90_or_AFF_A70[How to configure 10G or 25G cluster ports on a new cluster setup on AFF A1K, AFF A90 or AFF A70^]
* link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_convert_an_existing_cluster_from_10G_or_25G_cluster_ports_to_40G_or_100G_cluster_ports_on_an_AFF_A1K_AFF_A90_or_AFF_A70[How to convert an existing cluster from 10G or 25G cluster ports to 40G or 100G cluster ports on an AFF A1K, AFF A90 or AFF A70^]

If you cannot link up e0a or e0b cluster ports on the existing node to the cluster ports on the new node, see link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-166978[NetApp Bugs Online Bug ID CONTAP-166978^].
====

//BURT-1476241 13-Sep-2022
