---
sidebar: sidebar
permalink: upgrade-arl-auto-affa900/verify_upgrade_hardware.html
keywords: nodes, upgrade, verify, hardware
summary: Before starting the upgrade, verify that you have the correct hardware to upgrade controller models in the same chassis.
---
= Verify the upgrade hardware
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Before starting the upgrade, verify that you have the correct modules for your replacement system. If there are parts missing, contact technical support or your NetApp sales representative for assistance.

[cols=2*,options="header",cols="50,50"]
|===
|If you're upgrading from ...
|Replacement system must have ...
|AFF A250, AFF C250 
a|* Two controller modules and new IO modules
* An X60132A, 4-port 10/25GbE card card for two-node switchless upgrade configurations
|AFF A800, AFF C800
|Two controller modules, two NVRAMs, and new IO modules
a|* AFF A220 configured as an ASA
* AFF A220, AFF A200, AFF C190
* FAS2620, FAS2720
a|Two controller modules

If you're converting the existing system to a storage shelf so you can attach it to another system, the replacement system must also have two IO modules. 
a|* AFF A700 configured as an ASA
* AFF A700
* FAS9000
|Two controller and two NVRAM modules

|===

// 2024 DEC 9, AFFFASDOC-33
// 2024 APR 16, AFFFASDOC-32
// 2023 AUG 29, AFFFASDOC-78
// 2023 MAY 29, AFFFASDOC-39
//BURT 1452254, 2022-04-27
