---
sidebar: sidebar
permalink: upgrade-arl-manual-app/index.html
keywords:  controller, aggregate, relocation, flexarray, manual, upgrade, metrocluster
summary: "Using the manual ARL upgrade procedure to upgrade controller hardware running ONTAP 9.8 or later, relocating the ownership of non-root aggregates."
---

= Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
This procedure describes how to upgrade the controller hardware using aggregate relocation (ARL) for the following system configurations:

[cols=3*,options="header",cols="20,20,60"]
|===
|Method |ONTAP version |Supported systems

|Manual upgrade using ARL
|9.8 or later
a|* FAS system to FAS system
* FAS system to a system with FlexArray Virtualization Software or a V-Series system
* AFF system to AFF system
+
You can only upgrade to a replacement system in the same series:

** AFF A-Series system to AFF A-Series system
** AFF C-Series system to AFF C-Series system
* ASA system to ASA system
+
ASA upgrade to an ASA r2 replacement system is not supported. For information on migrating data from ASA to ASA r2, see link:https://docs.netapp.com/us-en/asa-r2/install-setup/set-up-data-access.html[Enable data access from SAN hosts to your ASA r2 storage system^].
+
You can only upgrade to a replacement system in the same series:

** ASA A-Series system to ASA A-Series system
** ASA C-Series system to ASA C-Series system
* System with FlexArray Virtualization Software or a V-Series system to a FAS system, provided that the system with FlexArray Virtualization Software or V-Series system has no array LUNs.
* V-Series system to a system with FlexArray Virtualization Software or a V-Series system
|===



include::../_include/ru_man_use_arl_overview.adoc[]

* In addition to non-MetroCluster configurations, this procedure applies to Fabric MetroCluster four-node and eight-node configurations running ONTAP 9.8 and later.

** For MetroCluster configurations running ONTAP 9.7 and earlier, go to link:other_references.html[References] to link to _Using Aggregate Relocation to Manually Upgrade Controller Hardware Running ONTAP 9.7 or Earlier_.

** For MetroCluster IP configurations and additional upgrade options for Fabric MetroCluster
configurations, go to link:other_references.html[References] to link to the _MetroCluster Upgrade and Expansion_ content.

// 2024 NOV 29, AFFFASDOC-282
// 2021 FEB 24,  Formatted from CMS
