---
sidebar: sidebar
permalink: upgrade-arl/index.html
keywords:  aggregate, relocation, moving, manual, upgrade, relocate, hardware
summary: Use aggregate relocation to upgrade controller hardware
---
= Choose your ARL upgrade procedure
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can upgrade controller hardware without disruption by using aggregate relocation (ARL). For other methods of upgrading your controller hardware, see link:../upgrade/upgrade-decide-to-use-this-guide.html[Upgrade by moving volumes or storage].

You nondisruptively upgrade the controller hardware on a pair of nodes running ONTAP by migrating non-root aggregates from the original nodes to the new nodes in the same cluster. The data hosted on the nodes that are being upgraded is accessible during the upgrade.

ARL takes advantage of the HA configuration to give you the capability to move ownership of non-root aggregates from one node to another if they share storage within the same cluster.

There are several ARL methods for upgrading your controller hardware. Before you start, you must verify that you have selected the correct method for your controller hardware upgrade. 

== Use "system controller replace" commands to upgrade controller models in the same chassis
Review the supported model matrix for upgrading controller hardware by converting the old system to the replacement system, keeping the old system chassis and disks.

[cols=3*,options="header",cols="20,20,40"]
|===
|Old system |Replacement system |Supported ONTAP versions

|AFF A220 configured as an All SAN Array (ASA) 
|ASA A150
|9.13.1P1 and later
|AFF A220
|AFF A150
|9.10.1P15, 9.11.1P11, 9.12.1P5 and later
|AFF A200
|AFF A150
a|9.10.1P15, 9.11.1P11 and later 

NOTE: AFF A200 does not support ONTAP versions later than 9.11.1.
|AFF C190
|AFF A150
|9.10.1P15, 9.11.1P11, 9.12.1P5 and later 

|FAS2620 
|FAS2820
a|9.11.1P7 (FAS2620)

NOTE: FAS2620 does not support ONTAP versions later than 9.11.1.

9.13.1 and later (FAS2820)
|FAS2720 |FAS2820	
|9.13.1 and later
|AFF A700 configured as an ASA 
|ASA A900
|9.13.1P1 and later
|AFF A700 
|AFF A900
|9.10.1P10, 9.11.1P6 and later
|FAS9000 |FAS9500
|9.10.1P10, 9.11.1P6 and later
|===

For more information on the upgrade considerations and limitations, see link:../upgrade-arl-auto-affa900/index.html[Overview].

== Use "system controller replace" commands with ONTAP 9.8 or later

Review the supported model matrix for upgrading controller hardware by using system controller replace commands on systems running ONTAP 9.8 or later.

|===
|Old controller |Replacement controller

|FAS8020, FAS8040, FAS8060, FAS8080
|FAS8200, FAS8300, FAS8700, FAS9000

|FAS8060, FAS8080
|FAS9500

|AFF8020, AFF8040, AFF8060, AFF8080
|AFF A300, AFF A400, AFF A700, AFF A800

|AFF8060, AFF8080
|AFF A900

|FAS8200
|FAS8300, FAS8700, FAS9000, FAS9500

|FAS8300, FAS8700, FAS9000
|FAS9500

|AFF A300
|AFF A400, AFF A700, AFF A800, AFF A900

|AFF A320
|AFF A400

|AFF A400, AFF A700
|AFF A900
|===

For more information on the upgrade considerations and limitations, see link:../upgrade-arl-auto-app/decide_to_use_the_aggregate_relocation_guide.html[Decide whether to use the aggregate relocation procedure].

== Use "system controller replace" with ONTAP 9.5 to 9.7

Review the supported model matrix for upgrading controller hardware by using system controller replace commands on systems running ONTAP 9.5 to 9.7.

[cols="50,50"]
|===
|Old controller |Replacement controller

|FAS8020, FAS8040, FAS8060, FAS8080
|FAS8200, FAS8300, FAS8700, FAS9000
|AFF8020, AFF8040, AFF8060, AFF8080
|AFF A300, AFF A400, AFF A700, AFF A800
|FAS8200
|FAS8700, FAS9000, FAS8300
|AFF A300
|AFF A700, AFF A800, AFF A400
|===

For more information on the upgrade considerations and limitations, see link:../upgrade-arl-auto/decide_to_use_the_aggregate_relocation_guide.html[Decide whether to use the aggregate relocation procedure]

== Use manual ARL commands

Review the supported systems for upgrading controller hardware by using manual commands on systems running ONTAP 9.

Supported systems:

* FAS system to FAS system
* FAS system to a system with FlexArray Virtualization Software or a V-Series system
* AFF system to AFF system
* System with FlexArray Virtualization Software or a V-Series system to a FAS system, provided that the system with FlexArray Virtualization Software or V-Series system has no array LUNs.
* V-Series system to a system with FlexArray Virtualization Software or a V-Series system

For more information on the upgrade considerations and limitations:

* For systems running ONTAP 9.8 and later, see link:../upgrade-arl-manual-app/decide_to_use_arl_guide.html[Decide whether to use the aggregate relocation procedure]
* For systems running ONTAP 9.7 and earlier, see link:../upgrade-arl-manual/decide_to_use_arl_guide.html[Decide whether to use the aggregate relocation procedure] 
 
// 2023 SEP 6, AFFFASDOC-78
// 24 FEB 2021:  formatted from CMS
